name: Build Basic Stack

on:
  - push
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: '[BUILD] | Install Dependencies'
        run: yarn install --frozen-lockfile
        shell: bash

      - name: '[BUILD] | Compile'
        run: yarn compile
        shell: bash

      - name: '[TEST] | Lint Check'
        run: yarn lint:check
        shell: bash
